# Generated by Django 5.1.3 on 2024-11-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditScore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditscore',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CreditScore.userprofile'),
        ),
    ]
